In [12]:
import numpy as np

In [13]:
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
target[:-1, [0,2]]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [15]:
target[np.ix_([True, False, True], [True, False, True])]

array([[0, 2],
       [6, 8]])

In [14]:
np.ix_([True, False, True], [True, False, True])

(array([[0],
        [2]]),
 array([[0, 2]]))

In [17]:
target[np.ix_([1,2], [True, False, True])]

array([[3, 5],
       [6, 8]])

In [18]:
new = target.reshape(-1)
new[new%2==0]

array([0, 2, 4, 6, 8])