In [1]:
import numpy as np
from scipy import linalg

In [3]:
A = np.array([[1, 35, 0],
              [0, 2, 3],
              [0, 0, 4]])

print(np.linalg.matrix_rank(A))

# linalg.inv计算逆矩阵
A_n = linalg.inv(A)
print(A_n)
print(np.dot(A, A_n))

3
[[  1.    -17.5    13.125]
 [  0.      0.5    -0.375]
 [  0.      0.      0.25 ]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
