In [2]:
import numpy as np

In [4]:
# np 对矩阵才能操作转置，对向量无效，所以这里要组织成矩阵形式
a = np.array([[1, 2, 3, 4]])
a

array([[1, 2, 3, 4]])

In [3]:
a.T

array([[1],
       [2],
       [3],
       [4]])

In [3]:
# 向量内积
u = np.array([3, 5, 7])
v = np.array([1, 4, 7])
np.dot(u, v)

72

In [5]:
u = np.array([3, 3, 9])
v = np.array([1, 4, 12])
np.cross(u, v)

array([  0, -27,   9])